### ISSUE TITLE
CSS结构化伪类选择器扫盲

### ISSUE THREAD

**Issue by Holybasil** [Holybasil/Blog#10]
### 前情提要

关于伪类选择器__:nth-child__，我想大部分人应该都跟我一样，平常用用`:nth-child(n)`来选择子元素中的某一项（不，就是我菜，菜是原罪），或者加上`:not(:nth-child(n))`来选择除了某个子元素的其他子元素。但是， 某一天，当我在用grid布局来实现一个简单的两列表格的时候，通过对`display:grid；grid-template-columns: repeat(2, 1fr)`的div中的span设置border来实现这个table的边框。为了维持每一条border均为1px，对于上下相邻的span只能取一个上方span的border-bottom或者下方span的border-top。最后，我决定，在`span{ border: 1px solid #ddd }`的情况下，除了第一行的两个span（也就是div中的前两个span），其他span的border-top均设置为none。代码类似下面：
```css
span{
    border: 1px solid #ddd;
}
span:not(:nth-child(1)), span:not(:nth-child(2)){
    border-top: none;
}
```
第一次需要同时设置两个子元素样式，代码写出来的时候有点点惊讶，怎么能这么不优雅（丑），重复的前缀太长，导致这段代码可读性也下降了不少。于是，一切为了好看，为了好看的一切，我重新学了一遍`:nth-child :nth-last-child :nth-of-type :last-of-type`四兄弟。

#### :nth-child
首先，我们有10个排排坐的div。
![10个div](https://i.loli.net/2019/06/13/5d01fac64351e10458.png)
```css
div{
    width: 30px;
    height: 30px;
    background-color: #f4606b;
}
```
:nth-child 其实应该写成:nth-child(an+b) (n=0,1,2,3...)
这样就能知道，他其实不仅可以选第1，2，3...位的子元素，当a=1时，选择的是从第n+b位子元素起到最后一位元素止的所有元素。也就是说，他可以用来确定一个范围。
比如，我们选择第4个子元素以及他之后的所有元素，如下：
![nth-child(n+4)](https://i.loli.net/2019/06/13/5d01fac64454d12611.png)
```css
div:nth-child(n+4){
    outline: #6b6575 dotted 4px;
    outline-offset: -12px;
}
```
那如果是选择某个子元素及之前的所有元素呢？
这个时候，a可以取-1，-n+b的取值区间此时为<=b，也就是选择前b位元素（注意：负数和零均没有意义）。比如，我们选择前6位子元素，如下：
![nth-child(-n)](https://i.loli.net/2019/06/13/5d0207efbb98a84854.png)
```css
div:nth-child(-n+6){
    ...
}
```
取前面的范围和后面的范围都有了，那么，中间呢？
简单，两个范围取交集就行了。
nth-child(n+b):nth-child(-n+b) 这样就会在两个范围内取交集，交集范围内的子元素被选择。如下：
![nth-child(n+4):nth-child(-n+6)](https://i.loli.net/2019/06/13/5d01fac644c6820985.png)
```css
div:nth-child(n+4):nth-child(-n+6){
    outline: #6b6575 dotted 4px;
    outline-offset: -12px;
}
```
这个效果是一层一层叠加的，可以想象成过滤器。最后漏下来的，就是被选择的子元素。
比如，我们选择之前交集中的偶数位子元素。如下：
![nth-child(n+4):nth-child(even):nth-child(-n+6)](https://i.loli.net/2019/06/13/5d01fac64473e60576.png)
```css
div:nth-child(n+4):nth-child(even):nth-child(-n+6){
    outline: #6b6575 dotted 4px;
    outline-offset: -12px;
}
```
多么强大的功能，理论上可以一次选择任何想要的范围，并且可读性非常强。

#### :nth-last-child
关于这个选择器，我是当作:nth-child的逆序选择器来看的。:nth-child默认从前往后选，:nth-last-child就是默认从后往前选。比如：

![](https://i.loli.net/2019/06/13/5d0207efbb98a84854.png)
```css
div:nth-last-child(n + 4){
    outline: #6b6575 dotted 4px;
    outline-offset: -12px;
}
```
这张图，其实我直接用的div:nth-child(-n+6)的效果图。
由于div总数为10，所以他们的效果一致。
再加上:not()的话，他们其实可以排列组合成各种相同的效果。举个例子：
```css
div:not(:nth-last-child(-n + 4)) {
    outline: #6b6575 dotted 4px;
    outline-offset: -12px;
}
```
上面代码的效果，与他们的效果，也是一致的。意为取非最后4个子元素，也就是前6个子元素。

#### :nth-of-type
为了说明这个伪类，我们在之前的10个div中混入10个span，如下：
![span](https://i.loli.net/2019/06/13/5d01fac60fe6c82932.png)
```css
span{
    border-radius: 50%;
    background-color: #c7b3e5;
}
```
现在，用:nth-child(even)选择偶数位的子元素，效果如下：
![nth-child](https://i.loli.net/2019/06/13/5d01fac60fdb552278.png)
```css
div:nth-child(even){
     outline: #6b6575 dotted 4px;
     outline-offset: -12px;
}
```
可以看到，只有标签为div且第偶数位的子元素被选择了。
然后，用:nth-of-type(even)选择偶数位的子元素
![nth-of-type](https://i.loli.net/2019/06/13/5d02059ec573531340.png)
```css
div:nth-of-type(even){
     outline: #6b6575 dotted 4px;
     outline-offset: -12px;
}
```
等等，这个偶数位好像有什么不对？
但是，这里就非常明显的反应出了:nth-child和:nth-of-type的区别。
- div:nth-child 选择当前元素的兄弟元素，然后按括号里的索引取值。所以，所有的子元素都会按顺序被标上索引。
- div:nth-of-type 选择与div相同标签名的兄弟元素，然后按括号里的索引取值。所以注意，只有拥有当前伪类选择器之前的选择器的dom才会被按顺序标上索引，不一致的就直接跳过了。

综上，在第二张图里，才会出现综合索引值为奇数的div被选择的情况。因为按照div来排索引，后三个div分别为6，8，10。

#### :nth-last-type
这里可以结合:nth-last-child，然后再注意一下:nth-of-type索引的主体就行了，这里就不赘述了。

#### :only-child与:only-of-type
想必到这里，关于这两个伪类选择器的使用，也应该非常清楚了。简而言之，若div:only-child{}生效，则说明此div是其父元素的唯一子元素。若div:only-of-type{}生效，则此div的父元素不一定只有一个子元素，而是只有一个标签为div的子元素（其他span p元素可能存在）。

over
