### ISSUE TITLE
关于echarts使用的注意事项

### ISSUE THREAD

**Issue by Holybasil** [Holybasil/Blog#8]
### 关于百度地图的引入
先[申请AK](http://lbsyun.baidu.com/apiconsole/key/create)，然后在项目的index.html的head中插入`<script src="https://api.map.baidu.com/api?v=2.0&ak=[申请到的AK]"></script>` ，这样表示有权使用。
然后，在项目文件里真正要用到的地方，`require("echarts/extension/bmap/bmap");`，（由于项目一般使用webpack且使用npm install echarts引入的echarts的package所以这样用）
最后，秉承着按需取用的原则，对charts模块的使用按需引入。（[按需引入的模块列表](https://github.com/ecomfe/echarts/blob/master/index.js)）

### clear与dispose的区别
在大多情况下，切换图标的展示方式，只需要调用chart实例的clear方法，将这个chart的option晴空万里，然后通过setOption加载另一套option就行了。但是，在对加载了bmap option的chart来说，clear方法只能将地图上的数据清除，并不能清除百度地图。所以这个时候，需要调用dispose方法，将这个chart实例清除，然后重新init，加载另一套数据。

### 及时去除事件监听
通常，在init一个chart之后，会加上 
```js
window.addEventListener("resize", () => {
    this.detailChart.resize();
});
```
来监听浏览器的窗口变化从而及时调整chart的宽高，但是记得在dispose之后，调用
```js
 window.removeEventListener("resize", () => {
    this.detailChart.resize();
});
```
及时移除监听。

### 关于chart按比例缩放
一般情况下，图表展示在浏览器的宽发生变化的情况下，宽高比例不变才是相对稳定的展示方式。所以展示一个chart的dom结构及css通常设置成是这样
```html
<div class="container">
    <div class="chart" ref="chart"></div>
</div>
```
```css
.container{
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 75%; // 宽高比 4:3
}
.chart{
    position:absolute;
    top: 0;
    left: 0;
    width: 100%;
    height:100%;
}
```
这里有一个技巧是一个div的padding的百分比是相对于自身的。所以这个时候.container就是一个固定比例的div。

### 一些题外话
在多个chart布局的时候，需要两列布局，且chart的个数是由数据决定的（也就是不确定最后会有多少行chart）。
这里我使用了grid布局，将外层div设置为
```css
div{
    display: grid;
    grid-template-columns: repeat(2, minmax(300px, 50%));
    grid-gap: 5%;
    box-sizing: border-box;
}
```
看起来超级完美啊，还有留白的间距，我真的是个设计的天才。
然而，渲染出来了以后，三行chart的最后一行直接超出了外层div的bottom border，这就不能接受了，可是为啥啊，明明列与列之间的gap就能被` box-sizing: border-box`限制的好好的，怎么行与行之间的就不行了呢？而且超出的部分刚好是三行chart中的两个gap的长度（手动微笑），也就是外层div的高度由子元素撑开，但是完全不管grid-row-gap。当然我也可以给外层div设置padding-bottom来辅助撑开。但是！由于数据的不确定性，padding-bottom可能是一个gap,也可能是两个gap，也可能是...打住！找了各种办法，完全找不到原因。最后放弃使用这个属性，行与行之间的间距改为子元素的margin-bottom，嗯，完美解决（并不）。
